
'.source.python':
  'debug.print':
    'prefix': 'dp'
    'body': 'print(f"\\\\n\\\\n debugging of $1: {$1}\\\\n\\\\n")'

  'debug.log':
    'prefix': 'dl'
    'body': 'import logging\nlogger = logging.getLogger("django.server")\nlogger.warning(f"\\\\n\\\\n logging of $1: {$1}\\\\n\\\\n")'

  'debug.pdb':
    'prefix': 'd'
    'body': 'import ipdb; ipdb.set_trace()'

  'assert.ErrorIn':
    'prefix': 'aei'
    'body': """
      expected_error_message = '${3:ErrorCoreMessage}'

      with self.assertRaises(${2:ErrorType}) as e:
        ${1:Call}
      self.assertIn(expected_error_message, str(e.exception))
    """
